import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="p-4 flex gap-2">
          <Link href="/" className="py-2 px-4 border-white border">
            Home
          </Link>
          <Link href="/random-number" className="py-2 px-4 border-white border">
            Random Number
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
